- name: prepare
  yum:
    name:
      - gcc
      - automake
      - libevent-devel
      - ncurses-devel
      # - glibc-static

- name: install tmux
  git:
    repo: https://github.com/tmux/tmux.git
    dest: ~/Documents/tmux
    version: "2.8"

- name: make tmux
  shell: sh autogen.sh && ./configure && make
  args:
    chdir: ~/Documents/tmux/

- name: copy tmux
  copy:
    src: ~/Documents/tmux/tmux
    dest: /usr/bin/tmux
    remote_src: yes
    mode: 0755

- name: clone config file
  when: USE_ME
  git:
    repo: https://github.com/shfshanyue/tmux-config.git 
    dest: ~/Documents/tmux-config

- name: clone config file (from .tmux)
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: ~/Documents/tmux-config
  when: not USE_ME

- name: copy config file (from .tmux)
  copy:
    src: ~/Documents/tmux-config/.tmux.conf.local
    dest: ~/.tmux.conf.local
    remote_src: yes
  when: not USE_ME

- name: copy config file
  copy:
    src: ~/Documents/tmux-config/.tmux.conf
    dest: ~/.tmux.conf
    remote_src: yes

- name: delete tmux-config 
  file:
    name: ~/Documents/tmux-config
    state: absent
